name: it@M Default Policy

codescanning:
  level: error

# Dependency Security Alerts
dependabot:
  level: high

# Dependency Licensing Alerts
licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*

  warnings:
    # Warning is the dependency isn't known
    ids:
      - Other
      - NA
  ignores:
    names:
      # false positive: reported als "GPL-3.0 AND MIT", ist aber MIT
      - escape-string-regexp
      # false positive: reported als "GPL-3.0 AND MIT", ist aber MIT
      - path-exists
      # false positive: reported als "GPL-3.0 AND MIT", ist aber MIT
      - slash
      # false positive: reported als "GPL-3.0 AND MIT", ist aber MIT
      - yocto-queue
      # false positive: reported als "GPL-2.0-or-later", ist aber MIT
      - load-script

secretscanning:
  level: all
